# Generated by Django 4.2.5 on 2023-09-23 17:48

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('first_class', 'First Class'), ('second_class', 'Second Class'), ('general', 'General')], max_length=20)),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('no_of_seats', models.SmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('train_no', models.CharField(db_index=True, max_length=5)),
                ('name', models.CharField(max_length=256)),
                ('destination', models.CharField(max_length=28)),
                ('source', models.CharField(max_length=28)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('travel_days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], size=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainCabin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('no_of_seats', models.SmallIntegerField()),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.cabin')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.train')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation_number', models.CharField(db_index=True, max_length=10)),
                ('no_of_seats', models.SmallIntegerField()),
                ('date_of_travel', models.DateField()),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.cabin')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.train')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
